//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam15
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsProducts
    {
        public int MaterialProductsId { get; set; }
        public Nullable<int> MaterialsProductsMaterialsLink { get; set; }
        public Nullable<int> MaterialsProductsProductsLink { get; set; }
        public Nullable<int> MaterialsProductsQuantity { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Products Products { get; set; }
    }
}
