//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam15
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.MaterialsProducts = new HashSet<MaterialsProducts>();
        }
    
        public int MaterialsId { get; set; }
        public string MaterialsName { get; set; }
        public Nullable<int> MaterialsTypeLink { get; set; }
        public Nullable<double> MaterialsMinPrice { get; set; }
        public Nullable<double> MaterialsQuantity { get; set; }
        public Nullable<double> MaterialsMinQuantity { get; set; }
        public Nullable<double> MaterialsInBox { get; set; }
        public string MaterialsUnit { get; set; }
    
        public virtual MaterialsType MaterialsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialsProducts> MaterialsProducts { get; set; }
    }
}
